### ISSUE TITLE
Rails Block bug

### ISSUE THREAD

**Issue by Ryan7214** [bergerhealer/TC-Coasters#4]
**TC Version:** latest
**BKCL Version:** latest
**TCC Version:** latest
**MC Server Version:** 1.12.2

**BUG:**
When setting the railsblock of a switcher to another location, it gets reset after a restart.

![image](https://user-images.githubusercontent.com/25272264/52011495-71a9cc80-24d8-11e9-9948-83f358ed140a.png)
Right was the railblock of a switcher
Left is the railsblock of a normal node

**Comment by weeryan17** [comment]
Please run the `/train version` command and get us the actual version numbers.

**Comment by Ryan7214** [comment]
I think it is pretty clear that 'latest' is the last version downloaded from https://ci.mg-dev.eu

**Comment by bbayu123** [comment]
Pretty sure 
1. 'latest' _usually_ refers to the releases, i.e. the version on Spigot, and that's exactly how I interpreted it in the first place.
2. The 'latest' version on Jenkins changes wildly so it's impossible to know what your 'latest' is.

However, based on the date this issue was made and me spending 10 seconds reading the Jenkins page, I would assume you are on BK 508, TC 445 and TCC 51

Now the questions would be,
1. Does this happen anywhere in the world?
2. Is this reproducible in a flat world?
3. If it is reproducible, what are the steps to reproduce the issue?

**Comment by Ryan7214** [comment]
1. Yes
2. Yes
3. Just change the railsblock of a switcher to another location and restart.

**Comment by bergerkiller** [comment]
Since I knew what server this was happening on it was sort of already clear this was in the latest development builds, but since this isn't public knowledge it's understandable it got overly verbose.

I'll have to look at this today if I'm not swamped by other things. My early assumption is that somewhere the 'dirty' flag isn't set for the node, so it doesn't save it.

What happens when you change the rail block, and then slightly move the node? Does it then work after a restart?

**Comment by Ryan7214** [comment]
It still gets reset.
![image](https://user-images.githubusercontent.com/25272264/52065596-22ff3f80-2577-11e9-8622-11232a590f3c.png)

**Comment by bergerkiller** [comment]
This takes care of it: https://github.com/bergerhealer/TC-Coasters/commit/da0cae6b64396e9ac005e53c4243da550eba8633

https://ci.mg-dev.eu/job/TC%20Coasters/52/
