### ISSUE TITLE
"Zip File Closed"

### ISSUE THREAD

**Issue by Kas-2** [bergerhealer/TC-Coasters#5]
I got an error last time, when i reload WorldGuard.

https://hastebin.com/zijorenete.makefile

**Comment by bergerkiller** [comment]
Did it cause a server crash or was a player disconnected? This happens because the packet handling is on another thread than the main one. I'm aware of some issues still existing when the packet handling interacts with TC as none of it is synchronized, though.

Luckily the packet handling doesn't write/modify any state so there's no risk of serious issues.

In this case, it thought a player was going to hit some minecart, but the minecart was destroyed on the main thread by the time it got to work with it.

**Comment by Kas-2** [comment]
No it wasnt when server crash or leaving, it just happens when player moves(and worldguard is just reloaded), but i think i fixed it, but investigating on my side is in progression.

**Comment by bergerkiller** [comment]
I meant more, as a result of this error. Does it have any effects besides the error itself being reported?

**Comment by Kas-2** [comment]
Uhh, yes it did, tracks didnt work, and the invisible armorstands became visible

**Comment by kascodingNL** [comment]
Can i have an respond please? Altrough it is already fixed by me, i would like to see it fixed in the code.

**Comment by bergerkiller** [comment]
Im not even sure that the error you saw is related to the bugs you saw, since the click-handling doesn't write any state. It might error out, but at worst it'll cause a player click to not be received, not anything like you're describing.

What's the fix you did yourself?

**Comment by Kas-2** [comment]
Somehow it worked when I switched versions, and after that switching back
